//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace house_management.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HOUSE_MANAGEMENTEntities : DbContext
    {
        public HOUSE_MANAGEMENTEntities()
            : base("name=HOUSE_MANAGEMENTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Account { get; set; }
        public virtual DbSet<Apartment> Apartment { get; set; }
        public virtual DbSet<House> House { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<TypeOfPayment> TypeOfPayment { get; set; }
    }
}
