//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace house_management.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Payment()
        {
            this.Apartment = new HashSet<Apartment>();
        }
    
        public int IdPayment { get; set; }
        public int TypeOfPaymentId { get; set; }
        public int SquarePrice { get; set; }
        public int LodgersPrice { get; set; }
        public int PaymentAmount { get; set; }
        public System.DateTime SupposedDatePayment { get; set; }
        public Nullable<System.DateTime> DateOfPayment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Apartment> Apartment { get; set; }
        public virtual TypeOfPayment TypeOfPayment { get; set; }
    }
}
